name: Publish to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # adjust to your preferred .NET Core version

    - name: Build solution
      run: dotnet build Kayki.StringUtils.sln --configuration Release

    - name: Run tests
      run: dotnet test Kayki.StringUtils/Kayki.StringUtilsTests.csproj --configuration Release

    - name: Publish package
      run: dotnet pack Kayki.StringUtils/Kayki.StringUtils.csproj --configuration Release --output ../artifacts
      working-directory: Kayki.StringUtils/Kayki.StringUtils/bin/Release

    - name: Set up NuGet
      uses: NuGet/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to GitHub Packages
      run: nuget push ../artifacts/*.nupkg --source "github"
