name: .NET

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build StringUtils Project
      run: dotnet build Kayki.StringUtils/Kayki.StringUtils.csproj -c Release
    - name: Build StringUtilsTests Project
      run: dotnet build Kayki.StringUtilsTests/Kayki.StringUtilsTests.csproj -c Release
    - name: Push Nuget
      run: |
        cd Kayki.StringUtils/out
        dotnet nuget push * .nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/kaykiletieri/index.json" --skip-duplicate
